# Generated by Django 5.2.1 on 2025-05-20 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phine_number',
            new_name='phone_number',
        ),
    ]
