# Generated by Django 5.2.1 on 2025-05-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('cod', 'Cash on Delivery')], default='transfer', max_length=20),
        ),
    ]
